### ISSUE TITLE
Initial build issue: util.lua:124 table index expected, got table

### ISSUE THREAD

**Issue by perfectsine** [demodude4u/Factorio-FBSR#144]
I've tried with verson 2.0.22 of space age and I've downloaded 2.0.16 from the steam console depot.  Same error:

Here is my config:

`
{
    "discord": {
        "bot_token": "",
        "command_prefix": "!",
        "reporting_user_id": "",
        "reporting_channel_id": "",
        "hosting_channel_id": ""
    },
    "reddit": {
        "credentials": {
            "username": "",
            "password": "",
            "client_id": "",
            "client_secret": ""
        },
        "subreddit": "",
        "summon_keyword": "!blueprint",
        "refresh_seconds": 20,
        "age_limit_hours": 24,
        "process_messages": true
    },
    "irc": {
        "server": "",
        "channel": "",
        "name": "",
        "password": "",
        "command": "!blueprint"
    },
    "webapi": {
        "bind": "0.0.0.0",
        "port": 8081,
        "use-local-storage": true,
        "local-storage": "./blueprint-images"
    },
    "watchdog": {
        "interval_minutes": 1
    },
    "logging": {
        "file": "log.txt"
    },
    "watchdog_interval_minutes": 1,
    "factorio": "{{FACTORIO_ROOT}}/"
}
`

`MOD FOLDER LOADED: core
MOD FOLDER LOADED: space-age
MOD FOLDER LOADED: quality
MOD FOLDER LOADED: elevated-rails
MOD FOLDER LOADED: base
LOAD ORDER:
 core
 base
 elevated-rails
 quality
 space-age
Nov 27, 2024 1:15:47 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service BlueprintBotDiscordService [FAILED] has failed in the STARTING state.
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.app.BlueprintBotDiscordService.startUp(BlueprintBotDiscordService.java:668)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)

SERVICE FAILURE: BlueprintBotDiscordService
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.app.BlueprintBotDiscordService.startUp(BlueprintBotDiscordService.java:668)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)
Exception in thread "main" java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[BlueprintBotRedditService [STARTING], WebAPIService [STARTING]], FAILED=[BlueprintBotDiscordService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:742)
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:555)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:304)
	at com.demod.fbsr.app.StartAllServices.main(StartAllServices.java:52)
MOD FOLDER LOADED: core
MOD FOLDER LOADED: space-age
MOD FOLDER LOADED: quality
MOD FOLDER LOADED: elevated-rails
MOD FOLDER LOADED: base
LOAD ORDER:
 core
 base
 elevated-rails
 quality
 space-age
MOD FOLDER LOADED: core
Nov 27, 2024 1:15:47 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service BlueprintBotRedditService [FAILED] has failed in the STARTING state.
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.FBSR.initialize(FBSR.java:720)
	at com.demod.fbsr.app.BlueprintBotRedditService.startUp(BlueprintBotRedditService.java:531)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:225)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

SERVICE FAILURE: BlueprintBotRedditService
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
MOD FOLDER LOADED: space-age	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)

	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.FBSR.initialize(FBSR.java:720)
	at com.demod.fbsr.app.BlueprintBotRedditService.startUp(BlueprintBotRedditService.java:531)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:225)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)MOD FOLDER LOADED: quality

MOD FOLDER LOADED: elevated-rails
MOD FOLDER LOADED: base
LOAD ORDER:
 core
 base
 elevated-rails
 quality
 space-age
2024-11-27 13:15:47.858 java[7394:43496154] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-27 13:15:47.860 java[7394:43496154] +[IMKInputSession subclass]: chose IMKInputSession_Modern
Nov 27, 2024 1:15:47 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service WebAPIService [FAILED] has failed in the STARTING state.
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.FBSR.initialize(FBSR.java:720)
	at com.demod.fbsr.app.WebAPIService.startUp(WebAPIService.java:69)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)

SERVICE FAILURE: WebAPIService
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.FBSR.initialize(FBSR.java:720)
	at com.demod.fbsr.app.WebAPIService.startUp(WebAPIService.java:69)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)
`

I am on MacOS with.
![Screenshot 2024-11-27 at 1 22 10 PM](https://github.com/user-attachments/assets/5e0af96e-c0cf-442a-933a-c5b9d2043fb4)
![image](https://github.com/user-attachments/assets/62a33d31-87be-4b33-a4da-10a55acef3dc)

**Comment by perfectsine** [comment]
I just realized you had a 2.0. branch and pulled it down.  Here are the new build errors:


MOD FOLDER LOADED: core
MOD FOLDER LOADED: space-age
MOD FOLDER LOADED: quality
MOD FOLDER LOADED: elevated-rails
MOD FOLDER LOADED: base
Nov 27, 2024 1:42:36 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service WebAPIService [FAILED] has failed in the STARTING state.
java.lang.Error: Unresolved compilation problem: 

	at com.demod.fbsr.FBSR.initialize(FBSR.java:650)
	at com.demod.fbsr.app.WebAPIService.startUp(WebAPIService.java:68)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)

Nov 27, 2024 1:42:36 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service BlueprintBotRedditService [FAILED] has failed in the STARTING state.
java.lang.Error: Unresolved compilation problem: 

	at com.demod.fbsr.FBSR.initialize(FBSR.java:650)
	at com.demod.fbsr.app.BlueprintBotRedditService.startUp(BlueprintBotRedditService.java:525)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:225)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

java.lang.Error: Unresolved compilation problem: 
SERVICE FAILURE: WebAPIService
	at com.demod.fbsr.FBSR.initialize(FBSR.java:650)
	at com.demod.fbsr.app.WebAPIService.startUp(WebAPIService.java:68)

	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)
SERVICE FAILURE: BlueprintBotRedditService
java.lang.Error: Unresolved compilation problem: 

	at com.demod.fbsr.FBSR.initialize(FBSR.java:650)
	at com.demod.fbsr.app.BlueprintBotRedditService.startUp(BlueprintBotRedditService.java:525)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:225)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Exception in thread "main" java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[BlueprintBotDiscordService [STARTING]], FAILED=[WebAPIService [FAILED], BlueprintBotRedditService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:742)
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:555)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:304)
	at com.demod.fbsr.app.StartAllServices.main(StartAllServices.java:52)
LOAD ORDER:
 core
 base
 elevated-rails
 quality
 space-age
Nov 27, 2024 1:42:36 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service BlueprintBotDiscordService [FAILED] has failed in the STARTING state.
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.app.BlueprintBotDiscordService.startUp(BlueprintBotDiscordService.java:495)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)

SERVICE FAILURE: BlueprintBotDiscordService
org.luaj.vm2.LuaError: @{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124 table index expected, got table
stack traceback:
	{{FACTORIO_ROOT}}/data/core/lualib/util.lua:124: in main chunk
	__MOD__/prototypes/style.lua:1: in main chunk
	core_/data.lua:2: in main chunk
	[Java]: in ?
	at org.luaj.vm2.LuaValue.typerror(Unknown Source)
	at org.luaj.vm2.LuaTable.set(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at org.luaj.vm2.lib.PackageLib$require.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at com.demod.factorio.FactorioData.loadStage(FactorioData.java:348)
	at com.demod.factorio.FactorioData.initializeDataTable(FactorioData.java:279)
	at com.demod.factorio.FactorioData.getTable(FactorioData.java:217)
	at com.demod.fbsr.app.BlueprintBotDiscordService.startUp(BlueprintBotDiscordService.java:495)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:750)


Please let me know if you have any suggesitons!

**Comment by demodude4u** [comment]
2.0 branch is not in a working state right now, I do not guarantee it will even compile at this time.  I'll try to remember to reach out to you when I get it working, sorry!

**Comment by perfectsine** [comment]
All good, I appreciate you and the project.  I am getting it wired into my new blueprints website and I'm looking forward to your work!!

**Comment by perfectsine** [comment]
@demodude4u  - Will the main branch work if I download regular factorio?

**Comment by demodude4u** [comment]
The last known version I have worked with main branch is factorio 1.1.94.  If you download that version, it should work.

**Comment by demodude4u** [comment]
> All good, I appreciate you and the project. I am getting it wired into my new blueprints website and I'm looking forward to your work!!

@perfectsine As a heads up, the current plan is to only support blueprint strings made in factorio 2.0 when the 2.0 branch goes live.  It will likely require some extra work to support blueprints from 1.x versions.

It might be possible for you to run two versions of the renderer at the same time (1.x and 2.0), and pick which one based on the version found in the blueprint string.

**Comment by perfectsine** [comment]
Hey @demodude4u - Got your work integrated:

https://www.factoriocodex.com/blueprints/35/recipe-details

Check the dropdowns for your images. 

I packed your rendere into it's own docker container and then connect it to my API, worked really well!

Each blueprint that's part of a blueprint string now gets rendered automatically.  When 2.X is ready, I'll be able to integrate it quick and easy.  Thanks!!!
